### ISSUE TITLE
Queue system

### ISSUE THREAD

**Issue by jamen** [jamen/osia#24]
I want to redesign tasks in a queue system, so that way when you do things like:
```javascript
osia.task('foo', ['bar'], () => ...);
osia.task('bar', () => ...);
```
And run:
```
$ osia foo bar
```
The `bar` task should not be run twice, but rather the system should see that it has already been queued.

I essentially want a way to track all of what tasks are being run, then run them all at the end, rather than as they are found (which is how it works currently).

**Comment by dustindowell22** [comment]
I think when you run the task

```
$ osia foo
```

Then bar should run behind the scenes. I don't think you should have to explicitly call `bar` as well, because then what's the point of adding `['bar']` to `foo`? That's how Gulp works anyway.

Also, how do you run tasks asynchronously as well as using the queue? Right now I can't really tell whether `['bar']` is part of the queue or also ran async. Stuff like Sass, Jade, and Coffee could be executed asynchronously most of the time, but sometimes you need to execute Sass and Jade async, then run something like Juice after both of those tasks have been complete so using the queue in that case would be useful.

**Comment by jamen** [comment]
You can define a task that depends on another:
```javascript
osia.task('foo', ['bar'], () => ...);
```
And run it:
```
$ osia foo
```
And it will start `bar`, if it is not running already.

If a task has dependencies not in the queue, they are added automatically.
